# This Dockerfile is used by CI to build the origin-web-console image.

FROM registry.svc.ci.openshift.org/openshift/release:nodejs-8-browser-tests AS builder
WORKDIR /go/src/github.com/openshift/origin-web-console
COPY . .
RUN npm install grunt && hack/install-deps.sh && chmod -R g+rwx $HOME && chgrp -R 0 $HOME && export PATH=$PATH:$(pwd)/node_modules/.bin
